In [2]:
import numpy as np

In [15]:
a = np.matrix([1, 2])
b = np.matrix([[3], [4]])
print(a)
print(b)

[[1 2]]
[[3]
 [4]]


In [16]:
print(a * b)
print(b * a)
# 1 * 3 + 2 * 4 = 11
# 
# 3  * 1 2 = [
# 4             [3 * 1, 3 * 2],
#               [4 * 1, 4 * 2]
#             ]


[[11]]
[[3 6]
 [4 8]]


In [17]:
a.shape

(1, 2)

In [18]:
b.shape

(2, 1)

In [42]:
print(b + a.transpose())

[[4]
 [6]]


In [40]:
layers = [2, 2, 1]
weights = [
    np.matrix([[2, 3], [4, 5]]), np.matrix([[1, 2]])
]
activations = [
    np.matrix([1]),  np.matrix([1])
]

class NeuralNetwork:
    def __init__(self, layers, weights, activations):
        self.layers = layers
        self.weights = weights
        self.activations = activations
        self.values = list(map(
            lambda x: np.zeros(x),
            layers
        ))
        print(self.values)

    def output(self, inputs):
        self.values[0] = input

        for layerIndex in range(0, len(self.layers) - 1):
            inputLayerIndex = layerIndex
            outputLayerIndex = layerIndex + 1
            outputLayerActivations = self.activations[inputLayerIndex]
            inputLayerValues = self.values[inputLayerIndex]
            inputWeights = self.weights[inputLayerIndex]
            print("Input weights", inputWeights, "Input layer values", inputLayerValues)
            weightedInputs = (inputWeights * inputLayerValues.transpose())
            print("Weighted inputs", weightedInputs)
            withActivation = weightedInputs + outputLayerActivations
            print("With activations", withActivation)
            self.values[outputLayerIndex] = np.arctan(withActivation).transpose()
            print("Values", self.values[outputLayerIndex])

        return self.values[len(self.layers) - 1]
    
    
network = NeuralNetwork(layers, weights, activations)

input = np.matrix([1, 2])
output = network.output(np.matrix([1, 2]))
print(output)

[array([0., 0.]), array([0., 0.]), array([0.])]
Input weights [[2 3]
 [4 5]] Input layer values [[1 2]]
Weighted inputs [[ 8]
 [14]]
With activations [[ 9]
 [15]]
Values [[1.46013911 1.50422816]]
Input weights [[1 2]] Input layer values [[1.46013911 1.50422816]]
Weighted inputs [[4.46859543]]
With activations [[5.46859543]]
Values [[1.3899323]]
[[1.3899323]]


[array([0., 0.]), array([0., 0.]), array([0.])]


Input weights [[2 3]
 [4 5]] Input layer values [[1 2]]


ValueError: shapes (2,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)